### ISSUE TITLE
NC v28 support

### ISSUE THREAD

**Issue by zenlord** [kirstenhh/nc-bpm-app#5] opened 2023-12-23 10:04 UTC
Hi,
I read that the Files app in NC 28 has been rewritten - I don't know what the impact is on the BPM Files app?
Could it be as simple as bumping the supported version?

**Comment by arnowelzel** [comment] 2023-12-26 16:03
No, that is not enough. You need to refactor the code for NC 28.

To get an idea what this means, see Draw.io which as also recently updated for NC 28:
https://github.com/jgraph/drawio-nextcloud/commit/f36b30b69b963fdd0d425b21d744bd43a04c3b71

**Comment by githubkoma** [comment] 2024-01-08 18:48
i had to refactor some code as well for NC28, as you can see here: https://github.com/githubkoma/multiboards/blob/main/js/filesintegration/src/index.js

and for that i had to look at https://github.com/jgraph/drawio-nextcloud/blob/main/src/main.js

**Comment by kirstenhh** [comment] 2024-01-17 14:58
Hi guys, 
Thus far (fingers crossed), it's been running with no issues beyond some CSS wonk on my tester instance with NC28. I'm still doing some last tests, but I'll probably push the update in a week or two.

**Comment by kirstenhh** [comment] 2024-02-19 14:19
> Still waiting...

Oh yeah no I'm an idiot and zenlord was right, I'm rewriting half the app because the way it was designed is nothing like any of the others I've been referencing and I genuinely have no idea how it was functioning till now, so it's gonna be a while.

**Comment by kirstenhh** [comment] 2024-02-28 10:42
The update is out, so I'm closing the issue. Please create a new one if there are any problems. (and @githubkoma thank you very much, I used quite a bit of your code as a basis for changes)

**Closed by kirstenhh** 2024-02-28 10:42 UTC
